import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
// @ts/ignore
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Providers from "@/redux/features/Providers";
import { Toaster } from "sonner";
import AppInitializer from "@/components/AppInitializer/AppInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${lato.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: lato.style.fontFamily }}
      >
        <Providers>
          <AppInitializer>
            <Toaster  />
            <Navbar />
            {children}
          </AppInitializer>
        </Providers>
      </body>
    </html>
  );
}
