import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
// @ts/ignore
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Providers from "@/redux/features/Providers";
import { Toaster } from "sonner";
import AppInitializer from "@/components/AppInitializer/AppInitializer";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Jurnee | Discover Local Events and Services",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${lato.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: lato.style.fontFamily }}
      >
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_API_KEY_CLIENT_ID || ""}
        >
          <Providers>
            <AppInitializer>
              <Toaster />
              <Navbar />
              {children}
            </AppInitializer>
          </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
